### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by Propolisa** [jtsorlinis/BoidsWebGPU#2]
Hi @jtsorlinis this is beautiful! I'd love to use it in a [small game I'm working on](https://github.com/Propolisa/cenote) for dust / creatures, but wanted to double check the license before I try to integrate it. 

Thanks,
Chris

**Comment by jtsorlinis** [comment]
Hey @Propolisa, I've just added an MIT license for it. Feel free to use it however you please and good luck with your game!
